name: atbash-cipher
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: Atbash
  source-dirs: src
  dependencies:
   - split
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - atbash-cipher
      - hspec
